### Variables para la petición http
@url = http://localhost:3000/api

### Create a new user
POST {{url}}/register
Content-Type: application/json

{
  "name": "Catherine Elizabeth Mendoza de Luna",
  "username": "eline",
  "email": "test@test.com",
  "password": "123456789",
  "birthday": "1997-05-27"
}

### Login a user
POST {{url}}/login
Content-Type: application/json

{
  "username": "eline",
  "password": "123456789"
}


