### Variables para la petición http
@url = http://localhost:3000/api
@token = 


### Create a new user
POST {{url}}/register
Content-Type: application/json

{
  "name": "Rogelio Trejo Estrada",
  "username": "trejoRogelio1",
  "email": "trejo.estrada.rogelio@gmail.com",
  "password": "123456789",
  "birthday": "2001-03-24"
}

### Login a user
POST {{url}}/login

{
  
}